### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by hex22a** [hex22a/post3ree-boilerplate#2]
npm WARN deprecated redux-simple-router@2.0.4: WARNING: This package has been renamed to react-router-redux. See https://github.com/rackt/react-router-redux/issues/80
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN prefer global react-tools@0.13.3 should be installed with -g

**Comment by Amazing-Space-Invader** [comment]
#3 close
