### ISSUE TITLE
Redux DevTools extension not working in Chrome

### ISSUE THREAD

**Issue by JasonSooter** [hex22a/post3ree-boilerplate#9]
In development mode, I am getting an error in the console that says "Redux DevTools could not render. Did you forget to include DevTools.instrument() in your store enhancer chain before using createStore()?"

Any ideas?

**Comment by hex22a** [comment]
@JasonSooter it seems like sometheng wrong with __DEV__ global variable. I'll fix it soon.

**Comment by hex22a** [comment]
it must be working now.
check patch 0.2.1

**Comment by JasonSooter** [comment]
Sorry for the delay. Gone on vacation to Mexico ;-)

Tried the updated/most recent build and Redux Devtools was working fine.

Thanks!
